### ISSUE TITLE
cannot upgrade venona

### ISSUE THREAD

**Issue by geekflyer** [codefresh-io/venona#50]
I'm trying to upgrade venona in our cluster but getting this error:
```
venona upgrade mycluster/codefresh
Error: an empty namespace may not be set when a resource name is provided%         
```

my kube context is already set to the appropriate namespace and cluster.

**Comment by olegsu** [comment]
@geekflyer
Mean while we are working to fixing the bug, you can reinstall Venona.
Note that you have to change the runtime environment of the pipelines that are running on your cluster, In case your cluster is been configured as default runtime environment, change it back to SAAS otherwide, change manually for each pipeline the runtime environment.
Then, you can delete venona `venona delete ....` and install it on the same namespace.
Will update here once this issue is resolved.

**Comment by olegsu** [comment]
@geekflyer a fix was pushed https://github.com/codefresh-io/venona/pull/53
Closing the issue atm.
